# Generated by Django 5.2.8 on 2025-11-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetailsView',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=80, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=150, null=True)),
                ('venue_location', models.CharField(blank=True, max_length=255, null=True)),
                ('organizer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('organizer_department', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'vw_event_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationSummaryView',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('total_registrations', models.IntegerField()),
                ('remaining_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_event_registration_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationsView',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('event_id', models.IntegerField()),
                ('event_title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('registration_status', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vw_user_registrations',
                'managed': False,
            },
        ),
    ]
